export const initialState = {
  world: {
    year: 1,
    totalPopulation: 5000,
    laborForce: 3000,
    children: 1000,
    elderly: 1000,

    farmlandAreaMu: 30000,
    baseGrainYieldPerMu: 500,
    grainYieldPerMu: 500,

    farmingLaborRequired: 3000,
    farmingLaborAllocated: 3000,
    laborAssignedCommerce: 0,
    idleLabor: 0,
    merchantCount: 0,
    farmEfficiency: 1,
    landUtilizationPercent: 100,

    shopCount: 0,
    operatingShops: 0,
    idleShops: 0,

    potentialGrainOutput: 15000000,
    actualGrainOutput: 15000000,
    lostGrainOutput: 0,

    grainDemandPerPerson: 400,
    grainDemandTotal: 0,
    grainBalance: 0,
    grainPerCapita: 0,
    grainCoverageRatio: 0,
    foodSecurityStatus: 'Unknown',
    foodSecurityIndex: 0,

    agriculturalTaxRate: 0.7,
    lastAgriculturalTax: 0,
    lastTaxCollectionYear: 0,
    grainTreasury: 15000000,
    saltReserve: 0,
    clothReserve: 0,
    saltPrice: 4.0,
    clothPrice: 2.0,
    saltAnnualSupply: 0,
    saltAnnualDemand: 0,
    saltImportQuota: 0,
    actualSaltImport: 0,
    saltConsumed: 0,
    saltShortfallRatio: 0,
    officialSaltPrice: 0,
    officialSaltAmount: 0,
    officialSaltSaleUsed: false,
    hempLandMu: 0,
    mulberryLandMu: 0,
    pendingHempLandMu: 0,
    pendingMulberryLandMu: 0,
    mulberryMaturationYear: 0,
    hempLaborRequired: 0,
    mulberryLaborRequired: 0,
    coarseClothOutput: 0,
    fineClothOutput: 0,
    rawSilkOutput: 0,
    mulberryMatureLandMu: 0,
    landDevelopmentFarmerIncomeBoost: 0,
    landDevelopmentCommerceBoost: 0,
    hempReclamationUsedThisYear: false,
    mulberryReclamationUsedThisYear: false,
    clothAnnualSupply: 0,
    clothAnnualDemand: 0,
    totalClothSupply: 0,
    localClothRatio: 0,
    blendedClothPrice: 2.0,
    clothImportQuota: 0,
    clothTradeReceived: 0,
    previousClothImportReceived: 0,
    localClothMilestone50Reached: false,
    localClothMilestone80Reached: false,
    clothImportReductionPenaltyApplied: false,
    playerSilkwormDung: 0,
    importedDung: 0,
    dungImportQuota: 0,
    totalDung: 0,
    dungCoverage: 0,
    fertilizerBonus: 1.0,
    paperMaterial: 0,
    paperMaterialReserve: 0,
    paperOutput: 0,
    hempStalks: 0,
    constructionCostReduction: 0,
    buildingFiber: 0,
    buildingFiberReserve: 0,
    structuralBonus: false,
    laborEfficiency: 1.0,
    grainAnnualDemand: 0,
    grainSurplus: 0,
    purchasingPower: 100,
    couponTreasury: 0,
    couponCirculating: 0,
    couponTotalIssued: 0,
    grainCouponsUnlocked: false,
    lastCouponIssueAmount: 0,
    lastCouponDenominationBreakdown: [],

    taxGrainRatio: 1.0,
    salaryGrainRatio: 1.0,
    totalSalaryCost: 0,
    lastSalaryCost: 0,
    couponSalaryPaymentWarning: false,

    totalGrainDemand: 0,
    grainPrice: 1.0,
    supplyRatio: 1.0,
    circulationRatio: 0,
    commerceActivityBonus: 1.0,
    backingRatio: 1.0,
    inflationRate: 0,

    farmerSatisfaction: 70,
    merchantSatisfaction: 70,
    officialSatisfaction: 70,
    landlordSatisfaction: 70,

    farmerIncomePool: 0,
    merchantIncomePool: 0,
    officialIncomePool: 0,
    farmlandRentRate: 0,
    lastFarmlandRentCollected: 0,

    creditCrisis: false,
    creditCrisisResolved: false,

    agricultureGDP: 0,
    commerceGDP: 0,
    constructionGDP: 0,
    gdpEstimate: 18000000,

    farmerIncomePerHead: 0,
    merchantIncomePerHead: 0,
    incomeGap: 0,

    stabilityIndex: 80,
    stabilityPenalty: 0,
    stabilityPenaltyReason: 'No penalty (income gap below 500)',
    efficiencyMultiplier: 1.0,

    maxMarketDemand: 0,
    demandSaturation: 0,
    demandShortfall: false,

    grainRedistributionUsed: false,
    merchantTaxUsed: false,

    householdRegistryActive: false,
    granaryLedgerActive: false,
    officialProclamationActive: false,
    contractSystemActive: false,
    codifiedLawPolicyActive: false,
    bureaucracyMaintenancePaid: 0,
    bureaucracyMaintenanceMissing: 0,

    saltTradeUsed: false,
    clothTradeUsed: false,
  },
  xikou: {
    population: 3000,
    laborForce: 1800,
    children: 600,
    elderly: 600,
    farmlandMu: 3000,
    mulberryLandMu: 1200,
    hempLandMu: 800,
    saltMines: 2,
    saltMineWorkers: 20,
    saltOutputJin: 200000,
    saltReserve: 0,
    grainTreasury: 500000,
    clothOutput: 0,
    stabilityIndex: 75,
    attitudeToPlayer: 0,
    diplomaticContact: false,
    farmWorkers: 300,
    mulberryWorkers: 120,
    idleLabor: 1380,
    farmEfficiency: 1,
    grainOutput: 1500000,
    silkwormDungOutput: 720000,
    silkwormDungAvailable: 0,
  },
  systems: {
    bankBuilt: false,
    bankClerksRecruited: false,
    antiCounterfeitResearched: false,
    grainCouponsUnlocked: false,
  },
  research: {
    currentTech: null,
    yearsRemaining: 0,
    completed: [],
    available: ['basic_farming', 'folk_trade', 'written_records', 'herbalism', 'militia'],
  },
  techBonuses: {
    grainYieldBonus: 0,
    stabilityBase: 80,
    populationGrowthBonus: 0,
    tradeEfficiency: 0,
    combatPower: 0,
    bureaucracyUnlocked: false,
    merchantSatisfactionBonus: 0,
    droughtResistance: false,
    defenseRating: 0,
    flourProcessing: false,
    lendingSystem: false,
    newTradePartners: false,
    scholarClass: false,
    espionageSystem: false,
    laborEfficiencyBonus: 0,
    commerceGDPMultiplierBonus: 0,
    officialSatisfactionBonus: 0,
    farmerSatisfactionBonus: 0,
  },
  policyHistory: [],
  yearLog: [],
  economyHistory: [],
};

export function createGameState() {
  const state = structuredClone(initialState);
  state.world.xikou = state.xikou;
  state.world.techBonuses = state.techBonuses;
  return state;
}
