import {
  INITIAL_POPULATION, INITIAL_LABOR_FORCE, INITIAL_CHILDREN, INITIAL_ELDERLY,
  INITIAL_FARMLAND_MU, BASE_GRAIN_YIELD_PER_MU, SALT_BASE_PRICE, CLOTH_BASE_PRICE,
  MONEYLENDER_LICENSE_FEE, MONEYLENDER_DEFAULT_TAX, BASE_STABILITY, FARMER_INIT_LITERACY,
  MERCHANT_POP_INIT_LITERACY, OFFICIAL_INIT_LITERACY, WORKER_INIT_LITERACY,
  SCHOOL_LICENSE_FEE, XIKOU_INIT_POPULATION, XIKOU_INIT_LABOR, XIKOU_FARMLAND_MU,
  XIKOU_MULBERRY_MU, XIKOU_HEMP_MU, XIKOU_SALT_OUTPUT
} from './config/constants.js';

export const initialState = {
  world: {
    farmlandAreaMu: INITIAL_FARMLAND_MU,
    baseGrainYieldPerMu: BASE_GRAIN_YIELD_PER_MU,
    grainYieldPerMu: BASE_GRAIN_YIELD_PER_MU,

    farmingLaborRequired: 3000,
    farmingLaborAllocated: 3000,
    commerceLaborAllocated: 0,
    hempLaborAllocated: 0,
    mulberryLaborAllocated: 0,
    farmEfficiency: 1,
    landUtilizationPercent: 100,
    farmingWage: 0,
    commerceWagePerWorker: 0,
    institutionWage: 0,
    hempWage: 0,
    mulberryWage: 0,
    averageWage: 0,
    laborFlowSummary: '',

    shopCount: 0,
    operatingShops: 0,
    idleShops: 0,

    potentialGrainOutput: 15000000,
    actualGrainOutput: 15000000,
    lostGrainOutput: 0,

    grainDemandPerPerson: 400,
    grainDemandTotal: 0,
    grainBalance: 0,
    grainPerCapita: 0,
    grainCoverageRatio: 0,
    foodSecurityStatus: 'Unknown',
    foodSecurityIndex: 0,

    lastAgriculturalTax: 0,
    lastTaxCollectionYear: 0,
    grainTreasury: 15000000,
    saltReserve: 0,
    clothReserve: 0,
    saltPrice: SALT_BASE_PRICE,
    clothPrice: CLOTH_BASE_PRICE,
    saltAnnualSupply: 0,
    saltAnnualDemand: 0,
    saltImportQuota: 0,
    actualSaltImport: 0,
    saltConsumed: 0,
    saltShortfallRatio: 0,
    officialSaltPrice: 0,
    officialSaltAmount: 0,
    officialSaltSaleUsed: false,
    hempLandMu: 0,
    mulberryLandMu: 0,
    pendingHempLandMu: 0,
    pendingMulberryLandMu: 0,
    mulberryMaturationYear: 0,
    coarseClothOutput: 0,
    fineClothOutput: 0,
    rawSilkOutput: 0,
    mulberryMatureLandMu: 0,
    landDevelopmentFarmerIncomeBoost: 0,
    landDevelopmentCommerceBoost: 0,
    hempReclamationUsedThisYear: false,
    mulberryReclamationUsedThisYear: false,
    clothAnnualSupply: 0,
    clothAnnualDemand: 0,
    totalClothSupply: 0,
    localClothRatio: 0,
    blendedClothPrice: CLOTH_BASE_PRICE,
    clothImportQuota: 0,
    clothTradeReceived: 0,
    previousClothImportReceived: 0,
    localClothMilestone50Reached: false,
    localClothMilestone80Reached: false,
    clothImportReductionPenaltyApplied: false,
    playerSilkwormDung: 0,
    importedDung: 0,
    dungImportQuota: 0,
    totalDung: 0,
    dungCoverage: 0,
    fertilizerBonus: 1.0,
    paperMaterial: 0,
    paperMaterialReserve: 0,
    paperOutput: 0,
    totalPaperDemand: 0,
    paperSupplyRatio: 1,
    hempStalks: 0,
    constructionCostReduction: 0,
    buildingFiber: 0,
    buildingFiberReserve: 0,
    structuralBonus: false,
    laborEfficiency: 1.0,
    grainAnnualDemand: 0,
    grainSurplus: 0,
    purchasingPower: 100,
    couponTreasury: 0,
    couponCirculating: 0,
    couponTotalIssued: 0,
    lockedGrainReserve: 0,
    grainCouponsUnlocked: false,
    lastCouponIssueAmount: 0,
    lastCouponDenominationBreakdown: [],

    taxGrainRatio: 1.0,
    salaryGrainRatio: 1.0,
    totalSalaryCost: 0,
    lastSalaryCost: 0,
    couponSalaryPaymentWarning: false,

    totalGrainDemand: 0,
    grainPrice: 1.0,
    supplyRatio: 1.0,
    circulationRatio: 0,
    commerceActivityBonus: 1.0,
    backingRatio: 1.0,
    inflationRate: 0,

    workerLifeQuality: 50,
    unemployed: 0,
    unemploymentRate: 0,
    institutionWorkers: 0,
    unemploymentStatus: '正常',

    lifeQualityFactors: {
      farmer: '',
      merchant: '',
      official: '',
      landlord: '',
    },
    lifeQualityChangeNotes: [],

    lastFarmlandRentCollected: 0,

    moneylenderShops: 0,
    approvedMoneylenders: 0,
    licenseFee: MONEYLENDER_LICENSE_FEE,
    moneylenderTaxRate: MONEYLENDER_DEFAULT_TAX,
    lendingPoolSize: 0,
    lendingPoolAvailable: 0,
    governmentDebt: 0,
    governmentDebtInterest: 0,
    governmentDebtCurrency: 'coupon',
    annualRepayment: 0,
    civilianLoanOutstanding: 0,
    civilianInvestmentProgress: 0,
    moneylenderGDP: 0,

    creditCrisis: false,
    creditCrisisResolved: false,

    grainGDP: 0,
    clothGDP: 0,
    agricultureGDP: 0,
    commerceGDP: 0,
    constructionGDP: 0,
    governmentGDP: 0,
    constructionSpendingThisYear: 0,
    gdpEstimate: 18000000,

    stabilityPenaltyReason: 'No penalty (income gap below 500)',

    maxMarketDemand: 0,
    demandSaturation: 0,
    demandShortfall: false,

    grainRedistributionUsed: false,
    merchantTaxUsed: false,

    householdRegistryActive: false,
    granaryLedgerActive: false,
    officialProclamationActive: false,
    contractSystemActive: false,
    codifiedLawPolicyActive: false,
    bureaucracyMaintenancePaid: 0,
    bureaucracyMaintenanceMissing: 0,

    saltTradeUsed: false,
    clothTradeUsed: false,

    farmerPopulation: 3000,
    merchantPopulation: 0,
    officialPopulation: 0,
    workerPopulation: 0,
    // DISABLED: reactivate with land privatization policy
    landlordPopulation: 0,

    literacyClassFlags: {
      merchantActive: false,
      officialActive: false,
      workerActive: false,
      landlordActive: false,
    },

    institutionPrereqBasicGov: false,
    institutionPrereqPolice: false,
    institutionPrereqCourt: false,
    institutionPrereqTradeBureau: false,
    institutionPrereqEngineeringBureau: false,
    literacyCaps: {
      farmer: 0.15,
      merchant: 0.4,
      official: 0.7,
      worker: 0.2,
      landlord: 0.35,
    },


    publicToilets: 0,
    roadLength: 0,
    toiletCoverage: 0,
    workerToToiletRatio: 0,
    workerToRoadRatio: 0,
    healthBureauPrereqAnnounced: false,
    tradeEfficiency: 0,
    reclaimEfficiency: 0,
    roadAttitudeBonus: 0,
    seniorOfficialWage: 0,
    midOfficialWage: 0,
    juniorOfficialWage: 0,
    professionalWage: 0,
    sanitationWorkerWage: 0,
    cleaningWorkerWage: 0,
    totalWageBill: 0,
    gdpPerCapita: 0,
    fireLeakageRate: 0.05,
    actualTaxRevenue: 0,
    theoreticalTaxRevenue: 0,
    fireLeakageFactors: '',
    officerWage: 0,
    policeEfficiencyTalent: 0,
    policeEfficiencyPaper: 0,
    policeEfficiencyStaffing: 0,
    policePaperInsufficient: false,
    policeStatusLabel: '未建立',
    policeEffectsSummary: '无',
    policeAnnualCost: 0,
    healthOfficerWage: 0,
    healthAnnualCost: 0,
    healthEfficiencyTalent: 0,
    healthEfficiencyPaper: 0,
    healthEfficiencyStaffing: 0,
    healthFactorsPositive: [],
    healthFactorsNegative: [],
    healthStatusLabel: '基线',
    healthGrowthModifier: 0,
    healthLifeQualityFarmerDelta: 0,
    healthLifeQualityAllDelta: 0,
    adminTalentDeployedHealth: 0,
    judgeWage: 0,
    courtEfficiencyTalent: 0,
    courtEfficiencyPaper: 0,
    courtEfficiencyStaffing: 0,
    creditRating: 'B',
    taxOfficerWage: 0,
    taxBureauEfficiencyTalent: 0,
    taxBureauEfficiencyPaper: 0,
    taxBureauEfficiencyStaffing: 0,
    commerceTaxRate: 0,
    landTaxRate: 0,
    commerceTaxRevenue: 0,
    merchantTaxArrears: 0,
    taxArrearsAccumulated: 0,
    landTaxRevenue: 0,
    taxBureauRevenueMultiplier: 1,
    tradeOfficerWage: 0,
    tradeBureauEfficiencyTalent: 0,
    tradeBureauEfficiencyPaper: 0,
    tradeBureauEfficiencyStaffing: 0,
    tradeBureauAnnualCost: 0,
    subsidyRate: 0,
    tradeBureauTradeBonus: 0,
    tradeQuotaBonus: 0,
    tradeBureauAttitudeDelta: 0,
    tradeProtectionQuotaCapRatio: 1,
    tradeSubsidyCost: 0,
    engineerWage: 0,
    engineeringBureauEfficiencyTalent: 0,
    engineeringBureauEfficiencyPaper: 0,
    engineeringBureauEfficiencyStaffing: 0,
    engineeringBureauAnnualCost: 0,
    pendingIrrigationCanals: 0,
    pendingCanals: [],
    wallReinforced: false,
    wallReinforcementInProgress: false,
    grainStorageCapacity: 50000000,
    grainStorageExpansions: 0,
    granaryExpansionInProgress: 0,
    engineeringConstructionReduction: 0,
    engineeringReclaimBonus: 0,
    infrastructureCostMultiplier: 1,
    constructionCostReductionBase: 0,
    policyExecutionEfficiency: 1,
    stabilityPenaltyLiteracyReduction: 0,
    textileOutputLiteracyBonus: 0,
    landReclaimEfficiency: 1,
    farmerLiteracyEfficiencyBonus: 0,
    merchantLiteracyEfficiencyBonus: 0,
  },
  buildings: {
    farmland: { count: 30000, method: 'manual_farming' },
    hemp_field: { count: 0, method: 'manual_hemp' },
    mulberry_field: { count: 0, method: 'manual_silk' },
    shop: { count: 0, method: 'basic_trade' },
    moneylender: { count: 0, method: 'basic_lending' },
    paper_mill: { count: 0, method: 'basic_papermaking' },
    lumber_yard: { count: 0, method: 'manual_logging' },
    blacksmith: { count: 0, method: 'basic_smithing' },
    kiln: { count: 0, method: 'basic_kiln' },
    medicine_hall: { count: 0, method: 'traditional_medicine' },
    inn: { count: 0, method: 'basic_inn' },
    tea_garden: { count: 0, method: 'manual_tea' },
    salt_field: { count: 0, method: 'solar_evaporation' },
    public_toilet: { count: 0, method: 'basic_sanitation' },
    road: { count: 0, method: 'dirt_road' },
    granary: { count: 0, method: 'basic_storage' },
    irrigation_canal: { count: 0, method: 'basic_irrigation' },
    city_wall: { count: 0, method: 'basic_fortification' },
    barracks: { count: 0, method: 'militia' },
    school_primary: { count: 0, method: 'basic_education' },
  },
  commodities: {
    grain: 0,
    salt: 0,
    cloth: 0,
    silk: 0,
    paper: 0,
    iron_tools: 0,
    weapons: 0,
    ceramics: 0,
    bricks: 0,
    lumber: 0,
    charcoal: 0,
    medicine: 0,
    tea: 0,
    silkworm_dung: 0,
    paper_material: 0,
    hemp_stalk: 0,
  },

  tradeContracts: [],

  commodityPrices: {
    grain: { price: 1.0, supply: 0, demand: 0, basePrice: 1.0, minPrice: 0.3, maxPrice: 5.0, elasticity: 0.5 },
    salt: { price: 4.0, supply: 0, demand: 0, basePrice: 4.0, minPrice: 1.0, maxPrice: 12.0, elasticity: 0.8 },
    cloth: { price: 2.0, supply: 0, demand: 0, basePrice: 2.0, minPrice: 0.5, maxPrice: 8.0, elasticity: 0.6 },
    silk: { price: 10.0, supply: 0, demand: 0, basePrice: 10.0, minPrice: 3.0, maxPrice: 30.0, elasticity: 0.4 },
    paper: { price: 3.0, supply: 0, demand: 0, basePrice: 3.0, minPrice: 1.0, maxPrice: 10.0, elasticity: 0.7 },
    iron_tools: { price: 8.0, supply: 0, demand: 0, basePrice: 8.0, minPrice: 2.0, maxPrice: 20.0, elasticity: 0.6 },
    weapons: { price: 15.0, supply: 0, demand: 0, basePrice: 15.0, minPrice: 5.0, maxPrice: 40.0, elasticity: 0.3 },
    ceramics: { price: 5.0, supply: 0, demand: 0, basePrice: 5.0, minPrice: 1.0, maxPrice: 15.0, elasticity: 0.5 },
    lumber: { price: 2.0, supply: 0, demand: 0, basePrice: 2.0, minPrice: 0.5, maxPrice: 8.0, elasticity: 0.6 },
    charcoal: { price: 1.5, supply: 0, demand: 0, basePrice: 1.5, minPrice: 0.3, maxPrice: 5.0, elasticity: 0.7 },
    medicine: { price: 6.0, supply: 0, demand: 0, basePrice: 6.0, minPrice: 2.0, maxPrice: 20.0, elasticity: 0.4 },
    tea: { price: 5.0, supply: 0, demand: 0, basePrice: 5.0, minPrice: 1.0, maxPrice: 15.0, elasticity: 0.5 },
    bricks: { price: 0.5, supply: 0, demand: 0, basePrice: 0.5, minPrice: 0.1, maxPrice: 2.0, elasticity: 0.8 },
  },
  privateSector: {
    farmerGrain: 4500000,
    farmerCoupons: 0,
    merchantCoupons: 0,
    merchantGrain: 0,
    merchantGoods: 0,
    totalPrivateGrain: 4500000,
    totalPrivateCoupons: 0,
  },
  calendar: {
    year: 1,
  },
  land: {
    farmlandAreaMu: INITIAL_FARMLAND_MU,
    hempLandMu: 0,
    mulberryLandMu: 0,
    pendingFarmlandMu: 0,
    pendingHempLandMu: 0,
    pendingMulberryLandMu: 0,
    mulberryMaturationYear: 0,
    reclaimedThisYear: 0,
    publicToilets: 0,
    roadLength: 0,
    toiletCoverage: 0,
    irrigationCanalCount: 0,
    pendingCanals: [],
    wallReinforced: false,
    grainStorageCapacity: 50000000,
    grainStorageExpansions: 0,
  },
  agriculture: {
    grainYieldPerMu: BASE_GRAIN_YIELD_PER_MU,
    baseGrainYieldPerMu: BASE_GRAIN_YIELD_PER_MU,
    grainTreasury: 15000000,
    actualGrainOutput: 0,
    potentialGrainOutput: 0,
    lostGrainOutput: 0,
    farmEfficiency: 1.0,
    landUtilizationPercent: 100,
    grainAnnualDemand: 0,
    grainSurplus: 0,
    fertilizerBonus: 1.0,
    dungCoverage: 0,
    totalDung: 0,
    playerSilkwormDung: 0,
    importedDung: 0,
    dungImportQuota: 0,
    constructionCostReduction: 0,
    buildingFiberReserve: 0,
    structuralBonus: false,
    laborEfficiency: 1.0,
    paperMaterialReserve: 0,
    paperOutput: 0,
    coarseClothOutput: 0,
    fineClothOutput: 0,
    rawSilkOutput: 0,
    totalClothOutput: 0,
  },
  fiscal: {
    agriculturalTaxRate: 0.7,
    taxGrainRatio: 1.0,
    salaryGrainRatio: 1.0,
    farmlandRentRate: 0,
    landTaxRate: 0,
    commerceTaxRate: 0,
    moneylenderTaxRate: MONEYLENDER_DEFAULT_TAX,
    fireLeakageRate: 0.05,
    actualTaxRevenue: 0,
    theoreticalTaxRevenue: 0,
    gdpPerCapita: 0,
    totalWageBill: 0,
    seniorOfficialWage: 0,
    midOfficialWage: 0,
    juniorOfficialWage: 0,
    professionalWage: 0,
    sanitationWorkerWage: 0,
    cleaningWorkerWage: 0,
    officerWage: 0,
    judgeWage: 0,
    taxOfficerWage: 0,
    tradeOfficerWage: 0,
    engineerWage: 0,
    healthOfficerWage: 0,
    subsidyRate: 0,
    annualRepayment: 0,
  },
  monetary: {
    couponTreasury: 0,
    couponCirculating: 0,
    couponTotalIssued: 0,
    lockedGrainReserve: 0,
    backingRatio: 1.0,
    inflationRate: 0,
    supplyRatio: 1.0,
    creditCrisis: false,
    creditCrisisResolved: false,
    creditRating: 'B',
    governmentDebt: 0,
    governmentDebtInterest: 0,
    lendingPoolSize: 0,
    lendingPoolAvailable: 0,
    civilianLoanOutstanding: 0,
    civilianInvestmentProgress: 0,
    moneylenderShops: 0,
    approvedMoneylenders: 0,
    licenseFee: MONEYLENDER_LICENSE_FEE,
    moneylenderGDP: 0,
    saltPrice: SALT_BASE_PRICE,
    clothPrice: CLOTH_BASE_PRICE,
    saltReserve: 0,
    clothReserve: 0,
    saltAnnualSupply: 0,
    saltAnnualDemand: 0,
    clothAnnualSupply: 0,
    clothAnnualDemand: 0,
    saltImportQuota: 0,
    actualSaltImport: 0,
    saltConsumed: 0,
    saltShortfallRatio: 0,
    officialSaltPrice: 0,
    officialSaltAmount: 0,
    officialSaltSaleUsed: false,
    clothImportQuota: 0,
    localClothRatio: 0,
    blendedClothPrice: CLOTH_BASE_PRICE,
    purchasingPower: 100,
    totalLivingCost: 0,
    giniRatio: 0,
  },
  classes: {
    farmerLifeQuality: 50,
    merchantLifeQuality: 50,
    officialLifeQuality: 50,
    // DISABLED: reactivate with land privatization policy
    landlordLifeQuality: 0,
    farmerSatisfaction: 50,
    merchantSatisfaction: 50,
    officialSatisfaction: 50,
    landlordSatisfaction: 0,
    farmerEventModifier: 0,
    merchantEventModifier: 0,
    officialEventModifier: 0,
    landlordEventModifier: 0,
    farmerSavings: 0,
    merchantSavings: 0,
    officialSavings: 0,
    landlordSavings: 0,
    farmerSavingsRate: 0,
    merchantSavingsRate: 0,
    officialSavingsRate: 0,
    landlordSavingsRate: 0,
    farmerIncomePerHead: 0,
    merchantIncomePerHead: 0,
    officialIncomePerHead: 0,
    landlordIncomePerHead: 0,
    farmerIncomePool: 0,
    merchantIncomePool: 0,
    officialIncomePool: 0,
    incomeGap: 0,
    stabilityIndex: BASE_STABILITY,
    stabilityPenalty: 0,
    efficiencyMultiplier: 1.0,
  },
  education: {
    commercialPrimarySchools: 0,
    commercialSecondarySchools: 0,
    govPrimaryCapacity: 0,
    govSecondaryCapacity: 0,
    govHigherCapacity: 0,
    primaryEnrolled: 0,
    secondaryEnrolled: 0,
    higherEnrolled: 0,
    schoolLicenseFee: SCHOOL_LICENSE_FEE,
    studentsDownToVillage: 0,
    adminTalentDeployedGov: 0,
    adminTalentDeployedPolice: 0,
    adminTalentDeployedCourt: 0,
    adminTalentDeployedTax: 0,
    commerceTalentDeployedTrade: 0,
    techTalentDeployedEngineering: 0,
    techTalentDeployedTax: 0,
  },
  institutions: {
    governmentEstablished: false,
    seniorOfficialCount: 0,
    midOfficialCount: 0,
    juniorOfficialCount: 0,
    professionalCount: 0,
    governmentEfficiency: 0,
    policeEstablished: false,
    policeOfficerCount: 0,
    policeRatio: 0,
    policeEfficiency: 0,
    healthBureauEstablished: false,
    healthOfficerCount: 0,
    healthEfficiency: 0,
    healthIndex: 50,
    consecutiveLowHealthYears: 0,
    diseaseOutbreak: false,
    courtEstablished: false,
    judgeCount: 0,
    courtEfficiency: 0,
    disputeRate: 0,
    taxBureauEstablished: false,
    taxOfficerCount: 0,
    taxBureauEfficiency: 0,
    tradeBureauEstablished: false,
    tradeOfficerCount: 0,
    tradeBureauEfficiency: 0,
    protectLocalCloth: false,
    tradeMonopolyGranted: false,
    newTradePartnerUnlocked: false,
    engineeringBureauEstablished: false,
    engineerCount: 0,
    engineeringBureauEfficiency: 0,
    irrigationCanalCount: 0,
    healthBureauPrereqMet: false,
    defenseRating: 0,
    bureaucracyUnlocked: false,
  },
  population: {
    totalPopulation: INITIAL_POPULATION,
    laborForce: INITIAL_LABOR_FORCE,
    children: INITIAL_CHILDREN,
    elderly: INITIAL_ELDERLY,
    infantPop: 500,
    childPop: 750,
    teenPop: 500,
    youthPop: 750,
    primeAdultPop: 1250,
    middleAgePop: 750,
    elderlyPop: 500,
    fertilityRate: 0.04,
    birthsThisYear: 0,
    deathsThisYear: 0,
    laborAssignedFarming: 0,
    laborAssignedCommerce: 0,
    commerceLaborAllocated: 0,
    laborIdle: 0,
    merchantCount: 0,
    hempLaborRequired: 0,
    mulberryLaborRequired: 0,
    sanitationWorkerCount: 0,
    cleaningWorkerCount: 0,
    farmerLiteracy: FARMER_INIT_LITERACY,
    merchantLiteracy: 0,
    officialLiteracy: 0,
    workerLiteracy: 0,
    landlordLiteracy: 0,
    overallLiteracy: FARMER_INIT_LITERACY,
    primaryGraduates: 0,
    secondaryGraduates: 0,
    higherGraduates: 0,
    annualPrimaryGrads: 0,
    annualSecondaryGrads: 0,
    annualHigherGrads: 0,
    secondaryEligiblePool: 0,
    higherEligiblePool: 0,
    higherSchoolUnlocked: false,
    adminTalent: 0,
    commerceTalent: 0,
    techTalent: 0,
    adminTalentDeployed: 0,
    commerceTalentDeployed: 0,
    techTalentDeployed: 0,
    scholarPool: 0,
  },
  xikou: {
    population: XIKOU_INIT_POPULATION,
    laborForce: XIKOU_INIT_LABOR,
    children: 600,
    elderly: 600,
    farmlandMu: XIKOU_FARMLAND_MU,
    mulberryLandMu: XIKOU_MULBERRY_MU,
    hempLandMu: XIKOU_HEMP_MU,
    saltMines: 2,
    saltMineWorkers: 20,
    saltOutputJin: XIKOU_SALT_OUTPUT,
    saltReserve: 0,
    grainTreasury: 500000,
    clothOutput: 0,
    clothReserve: 0,
    stabilityIndex: 75,
    attitudeToPlayer: 0,
    diplomaticContact: false,
    farmWorkers: 300,
    mulberryWorkers: 120,
    idleLabor: 1380,
    farmEfficiency: 1,
    grainOutput: 1500000,
    silkwormDungOutput: 720000,
    silkwormDungAvailable: 0,
  },

  mapState: {
    factions: [
      {
        id: 'player',
        name: '东陵城',
        x: 30,
        y: 55,
        type: 'player',
        discovered: true,
        size: 'large',
      },
      {
        id: 'xikou',
        name: '溪口村',
        x: 68,
        y: 38,
        type: 'village',
        discovered: false,
        size: 'medium',
      },
      {
        id: 'northern_traders',
        name: '北方商队',
        x: 52,
        y: 18,
        type: 'traders',
        discovered: false,
        size: 'small',
      },
    ],
    roads: [
      {
        from: 'player',
        to: 'xikou',
        level: 0,
      },
    ],
    selectedFaction: null,
    mapRevealed: false,
  },
  systems: {
    bankBuilt: false,
    bankClerksRecruited: false,
    antiCounterfeitResearched: false,
    grainCouponsUnlocked: false,
  },
  pops: [
    {
      id: 'pop_001',
      type: 'farmer',
      size: 30,
      wealth: 500,
      needs: { grain: 360, salt: 15, cloth: 0.3, medicine: 0.05 },
      needsSatisfied: { grain: 1, salt: 1, cloth: 1, medicine: 1 },
      politicalLeaning: 'conservative',
      literacy: FARMER_INIT_LITERACY,
      satisfaction: 50,
      income: 1500,
      savings: 0,
    },
    {
      id: 'pop_002',
      type: 'worker',
      size: 0,
      wealth: 500,
      needs: { grain: 360, salt: 15, cloth: 0.35, medicine: 0.08 },
      needsSatisfied: { grain: 1, salt: 1, cloth: 1, medicine: 1 },
      politicalLeaning: 'reformist',
      literacy: WORKER_INIT_LITERACY,
      satisfaction: 50,
      income: 0,
      savings: 0,
    },
    {
      id: 'pop_003',
      type: 'merchant',
      size: 0,
      wealth: 600,
      needs: { grain: 320, salt: 18, cloth: 0.45, medicine: 0.08 },
      needsSatisfied: { grain: 1, salt: 1, cloth: 1, medicine: 1 },
      politicalLeaning: 'conservative',
      literacy: MERCHANT_POP_INIT_LITERACY,
      satisfaction: 50,
      income: 0,
      savings: 0,
    },
    {
      id: 'pop_004',
      type: 'official',
      size: 0,
      wealth: 700,
      needs: { grain: 300, salt: 20, cloth: 0.5, medicine: 0.1 },
      needsSatisfied: { grain: 1, salt: 1, cloth: 1, medicine: 1 },
      politicalLeaning: 'conservative',
      literacy: OFFICIAL_INIT_LITERACY,
      satisfaction: 50,
      income: 0,
      savings: 0,
    },
  ],
  interestGroups: {
    farmerGuild: {
      id: 'farmerGuild',
      name: '农民公会',
      icon: '🌾',
      basedOn: 'farmer',
      size: 0,
      satisfaction: 50,
      power: 0,
      demands: { maxTaxRate: 0.6, minGrainPrice: 0.8, maxRentRate: 5, minFoodSecurity: 0.8 },
      currentDemandsMet: 0,
      politicalStance: 'conservative',
      supportedPolicies: ['grain_redistribution', 'reclaim_land', 'lower_tax'],
      opposedPolicies: ['merchant_tax', 'high_rent', 'conscription'],
      unlockCondition: null,
      yearsBelow20: 0,
      unlocked: true,
    },
    merchantGuild: {
      id: 'merchantGuild',
      name: '商人行会',
      icon: '💰',
      basedOn: 'merchant',
      size: 0,
      satisfaction: 50,
      power: 0,
      demands: { maxCommerceTaxRate: 0.15, minTradeEfficiency: 0.8, maxInflationRate: 0.1, minCreditRating: 'B' },
      currentDemandsMet: 0,
      politicalStance: 'reformist',
      supportedPolicies: ['trade_subsidy', 'contract_law', 'weights_measures', 'lower_commerce_tax'],
      opposedPolicies: ['trade_protection', 'merchant_tax', 'price_control'],
      unlockCondition: { minMerchants: 5 },
      yearsBelow20: 0,
      unlocked: false,
    },
    bureaucracy: {
      id: 'bureaucracy',
      name: '官僚集团',
      icon: '📜',
      basedOn: 'official',
      size: 0,
      satisfaction: 50,
      power: 0,
      demands: { minOfficialWage: 1.2, minPaperSupply: 0.7, maxFireLeakage: 0.15, minInstitutionCount: 3 },
      currentDemandsMet: 0,
      politicalStance: 'conservative',
      supportedPolicies: ['household_registry', 'codified_law', 'expand_bureaucracy'],
      opposedPolicies: ['reduce_officials', 'anti_corruption', 'civil_service_reform'],
      unlockCondition: { governmentEstablished: true },
      yearsBelow20: 0,
      unlocked: false,
    },
    military: {
      id: 'military',
      name: '军方',
      icon: '⚔️',
      basedOn: 'soldier',
      size: 0,
      satisfaction: 50,
      power: 0,
      demands: { minMilitaryBudget: 0.1, minWeaponsSupply: 0.8, minDefenseRating: 0.3, minBarracksCount: 1 },
      currentDemandsMet: 0,
      politicalStance: 'conservative',
      supportedPolicies: ['conscription', 'weapon_forging', 'fortification', 'expand_military'],
      opposedPolicies: ['disarmament', 'reduce_military_budget'],
      unlockCondition: { tech: 'militia' },
      yearsBelow20: 0,
      unlocked: false,
    },
    scholars: {
      id: 'scholars',
      name: '学者阶层',
      icon: '📚',
      basedOn: 'scholar',
      size: 0,
      satisfaction: 50,
      power: 0,
      demands: { minLiteracyRate: 0.2, minSchoolCount: 2, minResearchBudget: 0.05, minAdminTalent: 50 },
      currentDemandsMet: 0,
      politicalStance: 'reformist',
      supportedPolicies: ['imperial_exam', 'expand_schools', 'research_funding', 'papermaking'],
      opposedPolicies: ['anti_intellectualism', 'reduce_education'],
      unlockCondition: { secondaryGraduates: 10 },
      yearsBelow20: 0,
      unlocked: false,
    },
    craftsmen: {
      id: 'craftsmen',
      name: '工匠行会',
      icon: '🔨',
      basedOn: 'worker',
      size: 0,
      satisfaction: 50,
      power: 0,
      demands: { minWorkerWage: 0.8, minIronToolsSupply: 10, maxWorkHours: 1.0, minCraftBuildings: 1 },
      currentDemandsMet: 0,
      politicalStance: 'reformist',
      supportedPolicies: ['iron_tools_subsidy', 'craft_guild_rights', 'workshop_expansion'],
      opposedPolicies: ['price_control', 'foreign_goods_import'],
      unlockCondition: { buildings: ['blacksmith', 'kiln'] },
      yearsBelow20: 0,
      unlocked: false,
    },
  },
  research: {
    currentTech: null,
    yearsRemaining: 0,
    completed: [],
    available: ['basic_farming', 'folk_trade', 'written_records', 'herbalism', 'militia'],
  },
  techBonuses: {
    grainYieldBonus: 0,
    stabilityBase: 80,
    populationGrowthBonus: 0,
    tradeEfficiency: 0,
    combatPower: 0,
    bureaucracyUnlocked: false,
    merchantSatisfactionBonus: 0,
    droughtResistance: false,
    defenseRating: 0,
    flourProcessing: false,
    lendingSystem: false,
    newTradePartners: false,
    scholarClass: false,
    espionageSystem: false,
    laborEfficiencyBonus: 0,
    commerceGDPMultiplierBonus: 0,
    officialSatisfactionBonus: 0,
    farmerSatisfactionBonus: 0,
  },
  ledger: {
    taxRevenue: 0,
    rentRevenue: 0,
    commerceTaxRevenue: 0,
    landTaxRevenue: 0,
    moneylenderTaxRevenue: 0,
    couponTaxRevenue: 0,
    tradeRevenue: 0,
    debtBorrowed: 0,
    totalIncome: 0,

    wageBill: 0,
    researchCost: 0,
    constructionCost: 0,
    educationCost: 0,
    importCost: 0,
    subsidyCost: 0,
    debtRepayment: 0,
    debtInterest: 0,
    totalExpense: 0,

    netBalance: 0,

    farmerGrossIncome: 0,
    farmerTaxPaid: 0,
    farmerNetIncome: 0,
    farmerConsumption: 0,
    farmerSavingsChange: 0,

    merchantGrossIncome: 0,
    merchantTaxPaid: 0,
    merchantNetIncome: 0,
    merchantConsumption: 0,
    merchantSavingsChange: 0,

    officialGrossIncome: 0,
    officialNetIncome: 0,
    officialSavingsChange: 0,
  },
  ledgerHistory: [],
  policyHistory: [],
  yearLog: [],
  economyHistory: [],
};

const CALENDAR_FIELD_MAP = {
  year: 'year',
};

const POPULATION_FIELD_MAP = {
  totalPopulation: 'totalPopulation',
  laborForce: 'laborForce',
  children: 'children',
  elderly: 'elderly',
  infantPop: 'infantPop',
  childPop: 'childPop',
  teenPop: 'teenPop',
  youthPop: 'youthPop',
  primeAdultPop: 'primeAdultPop',
  middleAgePop: 'middleAgePop',
  elderlyPop: 'elderlyPop',
  fertilityRate: 'fertilityRate',
  birthsThisYear: 'birthsThisYear',
  deathsThisYear: 'deathsThisYear',
  laborAssignedFarming: 'laborAssignedFarming',
  laborAssignedCommerce: 'laborAssignedCommerce',
  commerceLaborAllocated: 'commerceLaborAllocated',
  laborIdle: 'laborIdle',
  merchantCount: 'merchantCount',
  hempLaborRequired: 'hempLaborRequired',
  mulberryLaborRequired: 'mulberryLaborRequired',
  sanitationWorkerCount: 'sanitationWorkerCount',
  cleaningWorkerCount: 'cleaningWorkerCount',
  farmerLiteracy: 'farmerLiteracy',
  merchantLiteracy: 'merchantLiteracy',
  officialLiteracy: 'officialLiteracy',
  workerLiteracy: 'workerLiteracy',
  landlordLiteracy: 'landlordLiteracy',
  overallLiteracy: 'overallLiteracy',
  primaryGraduates: 'primaryGraduates',
  secondaryGraduates: 'secondaryGraduates',
  higherGraduates: 'higherGraduates',
  annualPrimaryGrads: 'annualPrimaryGrads',
  annualSecondaryGrads: 'annualSecondaryGrads',
  annualHigherGrads: 'annualHigherGrads',
  secondaryEligiblePool: 'secondaryEligiblePool',
  higherEligiblePool: 'higherEligiblePool',
  higherSchoolUnlocked: 'higherSchoolUnlocked',
  adminTalent: 'adminTalent',
  commerceTalent: 'commerceTalent',
  techTalent: 'techTalent',
  adminTalentDeployed: 'adminTalentDeployed',
  commerceTalentDeployed: 'commerceTalentDeployed',
  techTalentDeployed: 'techTalentDeployed',
  scholarPool: 'scholarPool',
};

const LAND_FIELD_MAP = {
  farmlandAreaMu: 'farmlandAreaMu',
  hempLandMu: 'hempLandMu',
  mulberryLandMu: 'mulberryLandMu',
  pendingFarmlandMu: 'pendingFarmlandMu',
  pendingHempLandMu: 'pendingHempLandMu',
  pendingMulberryLandMu: 'pendingMulberryLandMu',
  mulberryMaturationYear: 'mulberryMaturationYear',
  reclaimedThisYear: 'reclaimedThisYear',
  publicToilets: 'publicToilets',
  roadLength: 'roadLength',
  toiletCoverage: 'toiletCoverage',
  irrigationCanalCount: 'irrigationCanalCount',
  pendingCanals: 'pendingCanals',
  wallReinforced: 'wallReinforced',
  grainStorageCapacity: 'grainStorageCapacity',
  grainStorageExpansions: 'grainStorageExpansions',
};

const AGRICULTURE_FIELD_MAP = {
  grainYieldPerMu: 'grainYieldPerMu',
  baseGrainYieldPerMu: 'baseGrainYieldPerMu',
  grainTreasury: 'grainTreasury',
  actualGrainOutput: 'actualGrainOutput',
  potentialGrainOutput: 'potentialGrainOutput',
  lostGrainOutput: 'lostGrainOutput',
  farmEfficiency: 'farmEfficiency',
  landUtilizationPercent: 'landUtilizationPercent',
  agriculturalTaxRate: 'agriculturalTaxRate',
  farmlandRentRate: 'farmlandRentRate',
  grainAnnualDemand: 'grainAnnualDemand',
  grainSurplus: 'grainSurplus',
  fertilizerBonus: 'fertilizerBonus',
  dungCoverage: 'dungCoverage',
  totalDung: 'totalDung',
  playerSilkwormDung: 'playerSilkwormDung',
  importedDung: 'importedDung',
  dungImportQuota: 'dungImportQuota',
  constructionCostReduction: 'constructionCostReduction',
  buildingFiberReserve: 'buildingFiberReserve',
  structuralBonus: 'structuralBonus',
  laborEfficiency: 'laborEfficiency',
  paperMaterialReserve: 'paperMaterialReserve',
  paperOutput: 'paperOutput',
  coarseClothOutput: 'coarseClothOutput',
  fineClothOutput: 'fineClothOutput',
  rawSilkOutput: 'rawSilkOutput',
  totalClothOutput: 'totalClothOutput',
};


const FISCAL_FIELD_MAP = {
  agriculturalTaxRate: 'agriculturalTaxRate',
  taxGrainRatio: 'taxGrainRatio',
  salaryGrainRatio: 'salaryGrainRatio',
  farmlandRentRate: 'farmlandRentRate',
  landTaxRate: 'landTaxRate',
  commerceTaxRate: 'commerceTaxRate',
  moneylenderTaxRate: 'moneylenderTaxRate',
  fireLeakageRate: 'fireLeakageRate',
  actualTaxRevenue: 'actualTaxRevenue',
  theoreticalTaxRevenue: 'theoreticalTaxRevenue',
  gdpPerCapita: 'gdpPerCapita',
  totalWageBill: 'totalWageBill',
  seniorOfficialWage: 'seniorOfficialWage',
  midOfficialWage: 'midOfficialWage',
  juniorOfficialWage: 'juniorOfficialWage',
  professionalWage: 'professionalWage',
  sanitationWorkerWage: 'sanitationWorkerWage',
  cleaningWorkerWage: 'cleaningWorkerWage',
  officerWage: 'officerWage',
  judgeWage: 'judgeWage',
  taxOfficerWage: 'taxOfficerWage',
  tradeOfficerWage: 'tradeOfficerWage',
  engineerWage: 'engineerWage',
  healthOfficerWage: 'healthOfficerWage',
  subsidyRate: 'subsidyRate',
  annualRepayment: 'annualRepayment',
};

const MONETARY_FIELD_MAP = {
  couponTreasury: 'couponTreasury',
  couponCirculating: 'couponCirculating',
  couponTotalIssued: 'couponTotalIssued',
  lockedGrainReserve: 'lockedGrainReserve',
  backingRatio: 'backingRatio',
  inflationRate: 'inflationRate',
  supplyRatio: 'supplyRatio',
  creditCrisis: 'creditCrisis',
  creditCrisisResolved: 'creditCrisisResolved',
  creditRating: 'creditRating',
  governmentDebt: 'governmentDebt',
  governmentDebtInterest: 'governmentDebtInterest',
  lendingPoolSize: 'lendingPoolSize',
  lendingPoolAvailable: 'lendingPoolAvailable',
  civilianLoanOutstanding: 'civilianLoanOutstanding',
  civilianInvestmentProgress: 'civilianInvestmentProgress',
  moneylenderShops: 'moneylenderShops',
  approvedMoneylenders: 'approvedMoneylenders',
  licenseFee: 'licenseFee',
  moneylenderGDP: 'moneylenderGDP',
  saltPrice: 'saltPrice',
  clothPrice: 'clothPrice',
  saltReserve: 'saltReserve',
  clothReserve: 'clothReserve',
  saltAnnualSupply: 'saltAnnualSupply',
  saltAnnualDemand: 'saltAnnualDemand',
  clothAnnualSupply: 'clothAnnualSupply',
  clothAnnualDemand: 'clothAnnualDemand',
  saltImportQuota: 'saltImportQuota',
  actualSaltImport: 'actualSaltImport',
  saltConsumed: 'saltConsumed',
  saltShortfallRatio: 'saltShortfallRatio',
  officialSaltPrice: 'officialSaltPrice',
  officialSaltAmount: 'officialSaltAmount',
  officialSaltSaleUsed: 'officialSaltSaleUsed',
  clothImportQuota: 'clothImportQuota',
  localClothRatio: 'localClothRatio',
  blendedClothPrice: 'blendedClothPrice',
  purchasingPower: 'purchasingPower',
  totalLivingCost: 'totalLivingCost',
  giniRatio: 'giniRatio',
};

const CLASS_FIELD_MAP = {
  farmerLifeQuality: 'farmerLifeQuality',
  merchantLifeQuality: 'merchantLifeQuality',
  officialLifeQuality: 'officialLifeQuality',
  landlordLifeQuality: 'landlordLifeQuality',
  farmerSatisfaction: 'farmerSatisfaction',
  merchantSatisfaction: 'merchantSatisfaction',
  officialSatisfaction: 'officialSatisfaction',
  landlordSatisfaction: 'landlordSatisfaction',
  farmerEventModifier: 'farmerEventModifier',
  merchantEventModifier: 'merchantEventModifier',
  officialEventModifier: 'officialEventModifier',
  landlordEventModifier: 'landlordEventModifier',
  farmerSavings: 'farmerSavings',
  merchantSavings: 'merchantSavings',
  officialSavings: 'officialSavings',
  landlordSavings: 'landlordSavings',
  farmerSavingsRate: 'farmerSavingsRate',
  merchantSavingsRate: 'merchantSavingsRate',
  officialSavingsRate: 'officialSavingsRate',
  landlordSavingsRate: 'landlordSavingsRate',
  farmerIncomePerHead: 'farmerIncomePerHead',
  merchantIncomePerHead: 'merchantIncomePerHead',
  officialIncomePerHead: 'officialIncomePerHead',
  landlordIncomePerHead: 'landlordIncomePerHead',
  farmerIncomePool: 'farmerIncomePool',
  merchantIncomePool: 'merchantIncomePool',
  officialIncomePool: 'officialIncomePool',
  incomeGap: 'incomeGap',
  stabilityIndex: 'stabilityIndex',
  stabilityPenalty: 'stabilityPenalty',
  efficiencyMultiplier: 'efficiencyMultiplier',
};

const EDUCATION_FIELD_MAP = {
  commercialPrimarySchools: 'commercialPrimarySchools',
  commercialSecondarySchools: 'commercialSecondarySchools',
  govPrimaryCapacity: 'govPrimaryCapacity',
  govSecondaryCapacity: 'govSecondaryCapacity',
  govHigherCapacity: 'govHigherCapacity',
  primaryEnrolled: 'primaryEnrolled',
  secondaryEnrolled: 'secondaryEnrolled',
  higherEnrolled: 'higherEnrolled',
  schoolLicenseFee: 'schoolLicenseFee',
  studentsDownToVillage: 'studentsDownToVillage',
  adminTalentDeployedGov: 'adminTalentDeployedGov',
  adminTalentDeployedPolice: 'adminTalentDeployedPolice',
  adminTalentDeployedCourt: 'adminTalentDeployedCourt',
  adminTalentDeployedTax: 'adminTalentDeployedTax',
  commerceTalentDeployedTrade: 'commerceTalentDeployedTrade',
  techTalentDeployedEngineering: 'techTalentDeployedEngineering',
  techTalentDeployedTax: 'techTalentDeployedTax',
};

const INSTITUTION_FIELD_MAP = {
  governmentEstablished: 'governmentEstablished',
  seniorOfficialCount: 'seniorOfficialCount',
  midOfficialCount: 'midOfficialCount',
  juniorOfficialCount: 'juniorOfficialCount',
  professionalCount: 'professionalCount',
  governmentEfficiency: 'governmentEfficiency',
  policeEstablished: 'policeEstablished',
  policeOfficerCount: 'policeOfficerCount',
  policeRatio: 'policeRatio',
  policeEfficiency: 'policeEfficiency',
  healthBureauEstablished: 'healthBureauEstablished',
  healthOfficerCount: 'healthOfficerCount',
  healthEfficiency: 'healthEfficiency',
  healthIndex: 'healthIndex',
  consecutiveLowHealthYears: 'consecutiveLowHealthYears',
  diseaseOutbreak: 'diseaseOutbreak',
  courtEstablished: 'courtEstablished',
  judgeCount: 'judgeCount',
  courtEfficiency: 'courtEfficiency',
  disputeRate: 'disputeRate',
  taxBureauEstablished: 'taxBureauEstablished',
  taxOfficerCount: 'taxOfficerCount',
  taxBureauEfficiency: 'taxBureauEfficiency',
  tradeBureauEstablished: 'tradeBureauEstablished',
  tradeOfficerCount: 'tradeOfficerCount',
  tradeBureauEfficiency: 'tradeBureauEfficiency',
  protectLocalCloth: 'protectLocalCloth',
  tradeMonopolyGranted: 'tradeMonopolyGranted',
  newTradePartnerUnlocked: 'newTradePartnerUnlocked',
  engineeringBureauEstablished: 'engineeringBureauEstablished',
  engineerCount: 'engineerCount',
  engineeringBureauEfficiency: 'engineeringBureauEfficiency',
  irrigationCanalCount: 'irrigationCanalCount',
  healthBureauPrereqMet: 'healthBureauPrereqMet',
  defenseRating: 'defenseRating',
  bureaucracyUnlocked: 'bureaucracyUnlocked',
};

function defineCompatAccessors(state) {
  Object.entries(CALENDAR_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.calendar[sourceField],
      set: (value) => {
        state.calendar[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.entries(POPULATION_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.population[sourceField],
      set: (value) => {
        state.population[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.entries(LAND_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.land[sourceField],
      set: (value) => {
        state.land[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.entries(AGRICULTURE_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.agriculture[sourceField],
      set: (value) => {
        state.agriculture[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });


  Object.entries(FISCAL_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.fiscal[sourceField],
      set: (value) => {
        state.fiscal[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.entries(MONETARY_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.monetary[sourceField],
      set: (value) => {
        state.monetary[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.entries(CLASS_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.classes[sourceField],
      set: (value) => {
        state.classes[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.entries(EDUCATION_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.education[sourceField],
      set: (value) => {
        state.education[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.entries(INSTITUTION_FIELD_MAP).forEach(([legacyField, sourceField]) => {
    Object.defineProperty(state.world, legacyField, {
      get: () => state.institutions[sourceField],
      set: (value) => {
        state.institutions[sourceField] = value;
      },
      enumerable: true,
      configurable: true,
    });
  });

  Object.defineProperty(state.world, '__calendar', {
    value: state.calendar,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__population', {
    value: state.population,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__pops', {
    value: state.pops,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__interestGroups', {
    value: state.interestGroups,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__land', {
    value: state.land,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__agriculture', {
    value: state.agriculture,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__fiscal', {
    value: state.fiscal,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__monetary', {
    value: state.monetary,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__classes', {
    value: state.classes,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__education', {
    value: state.education,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__institutions', {
    value: state.institutions,
    writable: true,
    enumerable: false,
    configurable: true,
  });
  Object.defineProperty(state.world, '__privateSector', {
    value: state.privateSector,
    writable: true,
    enumerable: false,
    configurable: true,
  });
}

export function ensureCommodityState(state) {
  if (!state || !state.world) return;

  state.buildings = state.buildings ?? {};
  state.commodities = state.commodities ?? {};
  state.commodityPrices = state.commodityPrices ?? {};

  const grainTreasury = Math.max(0, Number(state.world.grainTreasury ?? state.agriculture?.grainTreasury ?? 15000000));
  const saltReserve = Math.max(0, Number(state.world.saltReserve ?? 0));
  const clothReserve = Math.max(0, Number(state.world.clothReserve ?? 0));
  const rawSilkOutput = Math.max(0, Number(state.world.rawSilkOutput ?? 0));

  const commodityDefaults = {
    grain: grainTreasury,
    salt: saltReserve,
    cloth: clothReserve,
    silk: rawSilkOutput,
    paper: 0,
    iron_tools: 0,
    weapons: 0,
    ceramics: 0,
    bricks: 0,
    lumber: 0,
    charcoal: 0,
    medicine: 0,
    tea: 0,
    silkworm_dung: 0,
    paper_material: 0,
    hemp_stalk: 0,
  };

  Object.entries(commodityDefaults).forEach(([commodity, defaultValue]) => {
    const currentValue = state.commodities[commodity];
    state.commodities[commodity] = Math.max(
      0,
      Number(currentValue === undefined || currentValue === null ? defaultValue : currentValue)
    );
  });

  state.world.marketGrainInventory = state.commodities.grain;
  state.world.marketSaltInventory = state.commodities.salt;
  state.world.marketClothInventory = state.commodities.cloth;

  state.agriculture.grainTreasury = state.world.grainTreasury;
  state.agriculture.rawSilkOutput = state.world.rawSilkOutput;

  Object.entries(initialState.commodityPrices ?? {}).forEach(([commodity, defaults]) => {
    const current = state.commodityPrices[commodity] ?? {};
    state.commodityPrices[commodity] = {
      ...defaults,
      ...current,
      supply: Math.max(0, Number(current.supply ?? defaults.supply ?? 0)),
      demand: Math.max(0, Number(current.demand ?? defaults.demand ?? 0)),
      price: Math.max(0, Number(current.price ?? defaults.price ?? defaults.basePrice ?? 1)),
      lastPrice: Math.max(0, Number(current.lastPrice ?? current.price ?? defaults.price ?? defaults.basePrice ?? 1)),
      trend: current.trend ?? '→',
    };
  });

  state.world.commodityPrices = state.commodityPrices;
}

export function createGameState() {
  const state = structuredClone(initialState);

  defineCompatAccessors(state);
  state.world.techBonuses = state.techBonuses;
  state.world.ledger = state.ledger;
  state.world.pendingMulberryProjects = [];
  state.world.__buildings = state.buildings;
  state.world.__commodities = state.commodities;
  state.world.__pops = state.pops;
  state.world.__interestGroups = state.interestGroups;

  ensureCommodityState(state);

  return state;
}
