export const BUILDING_TYPES = [
  {
    id: 'farmland',
    name: '农田',
    category: 'agriculture',
    description: '基础粮食生产地块。',
    unit: '亩',
    baseWorkers: 0.1,
    baseOutputs: { grain: 500 },
    baseInputs: {},
    constructionCost: { grain: 0 },
    productionMethods: ['manual_farming', 'improved_plow', 'irrigated_farming'],
  },
  {
    id: 'hemp_field',
    name: '麻田',
    category: 'agriculture',
    description: '产出麻秆与造纸原料。',
    unit: '亩',
    baseWorkers: 0.1,
    baseOutputs: { hemp_stalk: 120, paper_material: 40 },
    baseInputs: {},
    constructionCost: { grain: 8 },
    productionMethods: ['manual_hemp', 'rotational_hemp'],
  },
  {
    id: 'mulberry_field',
    name: '桑田',
    category: 'agriculture',
    description: '产出生丝与蚕沙。',
    unit: '亩',
    baseWorkers: 0.1,
    baseOutputs: { silk: 40, silkworm_dung: 25 },
    baseInputs: {},
    constructionCost: { grain: 15 },
    productionMethods: ['manual_silk', 'intensive_sericulture'],
  },
  {
    id: 'shop',
    name: '商铺',
    category: 'commerce',
    description: '基础流通节点。',
    unit: '间',
    baseWorkers: 5,
    baseOutputs: {},
    baseInputs: { grain: 200 },
    constructionCost: { grain: 2000 },
    productionMethods: ['basic_trade', 'bookkeeping_trade'],
  },
  {
    id: 'moneylender',
    name: '钱庄',
    category: 'commerce',
    description: '提供借贷服务。',
    unit: '家',
    baseWorkers: 4,
    baseOutputs: {},
    baseInputs: { paper: 10 },
    constructionCost: { grain: 5000 },
    productionMethods: ['basic_lending', 'formal_lending'],
  },
  {
    id: 'paper_mill',
    name: '纸坊',
    category: 'industry',
    description: '将麻料加工为纸。',
    unit: '座',
    baseWorkers: 8,
    baseOutputs: { paper: 120 },
    baseInputs: { paper_material: 100, hemp_stalk: 60 },
    constructionCost: { grain: 8000 },
    productionMethods: ['basic_papermaking', 'alkaline_pulping'],
  },
  {
    id: 'lumber_yard',
    name: '木场',
    category: 'industry',
    description: '产出木材与木炭。',
    unit: '处',
    baseWorkers: 10,
    baseOutputs: { lumber: 180, charcoal: 70 },
    baseInputs: {},
    constructionCost: { grain: 6000 },
    productionMethods: ['manual_logging', 'saw_logging'],
  },
  {
    id: 'blacksmith',
    name: '铁匠铺',
    category: 'industry',
    description: '制造铁制工具与兵器。',
    unit: '间',
    baseWorkers: 6,
    baseOutputs: { iron_tools: 60, weapons: 20 },
    baseInputs: { charcoal: 40, lumber: 20 },
    constructionCost: { grain: 7000 },
    productionMethods: ['basic_smithing', 'water_hammer_smithing'],
  },
  {
    id: 'kiln',
    name: '窑场',
    category: 'industry',
    description: '烧制陶器与砖瓦。',
    unit: '座',
    baseWorkers: 7,
    baseOutputs: { ceramics: 120, bricks: 140 },
    baseInputs: { charcoal: 20, lumber: 10 },
    constructionCost: { grain: 6500 },
    productionMethods: ['basic_kiln', 'high_temp_kiln'],
  },
  {
    id: 'medicine_hall',
    name: '药堂',
    category: 'services',
    description: '供应草药与基础诊疗。',
    unit: '所',
    baseWorkers: 5,
    baseOutputs: { medicine: 80 },
    baseInputs: { tea: 10, paper: 5 },
    constructionCost: { grain: 5500 },
    productionMethods: ['traditional_medicine', 'compound_medicine'],
  },
  {
    id: 'inn',
    name: '客栈',
    category: 'services',
    description: '承接旅客与转运。',
    unit: '家',
    baseWorkers: 6,
    baseOutputs: {},
    baseInputs: { grain: 100, tea: 20 },
    constructionCost: { grain: 5000 },
    productionMethods: ['basic_inn', 'caravan_inn'],
  },
  {
    id: 'tea_garden',
    name: '茶园',
    category: 'agriculture',
    description: '产出茶叶商品。',
    unit: '亩',
    baseWorkers: 0.12,
    baseOutputs: { tea: 90 },
    baseInputs: {},
    constructionCost: { grain: 12 },
    productionMethods: ['manual_tea', 'terrace_tea'],
  },
  {
    id: 'salt_field',
    name: '盐田',
    category: 'industry',
    description: '晒盐场。',
    unit: '片',
    baseWorkers: 10,
    baseOutputs: { salt: 800 },
    baseInputs: {},
    constructionCost: { grain: 12000 },
    productionMethods: ['solar_evaporation', 'brine_boiling'],
  },
  {
    id: 'public_toilet',
    name: '公厕',
    category: 'infrastructure',
    description: '基础卫生设施。',
    unit: '座',
    baseWorkers: 1,
    baseOutputs: {},
    baseInputs: { lumber: 5, bricks: 10 },
    constructionCost: { grain: 2000 },
    productionMethods: ['basic_sanitation', 'sealed_sanitation'],
  },
  {
    id: 'road',
    name: '道路',
    category: 'infrastructure',
    description: '提升运输效率。',
    unit: '里',
    baseWorkers: 0.5,
    baseOutputs: {},
    baseInputs: { bricks: 8, lumber: 4 },
    constructionCost: { grain: 600 },
    productionMethods: ['dirt_road', 'stone_road'],
  },
  {
    id: 'granary',
    name: '粮仓',
    category: 'infrastructure',
    description: '增强储粮能力。',
    unit: '座',
    baseWorkers: 2,
    baseOutputs: {},
    baseInputs: { lumber: 20, bricks: 30 },
    constructionCost: { grain: 9000 },
    productionMethods: ['basic_storage', 'ventilated_storage'],
  },
  {
    id: 'irrigation_canal',
    name: '灌溉渠',
    category: 'infrastructure',
    description: '提升农业产能。',
    unit: '段',
    baseWorkers: 3,
    baseOutputs: {},
    baseInputs: { lumber: 10, bricks: 30 },
    constructionCost: { grain: 12000 },
    productionMethods: ['basic_irrigation', 'gated_irrigation'],
  },
  {
    id: 'city_wall',
    name: '城墙',
    category: 'military',
    description: '提升防御。',
    unit: '段',
    baseWorkers: 4,
    baseOutputs: {},
    baseInputs: { bricks: 80, lumber: 20 },
    constructionCost: { grain: 20000 },
    productionMethods: ['basic_fortification', 'reinforced_fortification'],
  },
  {
    id: 'barracks',
    name: '兵营',
    category: 'military',
    description: '驻军与训练设施。',
    unit: '座',
    baseWorkers: 8,
    baseOutputs: { weapons: 10 },
    baseInputs: { grain: 300, iron_tools: 10 },
    constructionCost: { grain: 16000 },
    productionMethods: ['militia', 'standing_army'],
  },
  {
    id: 'school_primary',
    name: '初级学堂',
    category: 'services',
    description: '基础教育设施。',
    unit: '所',
    baseWorkers: 4,
    baseOutputs: {},
    baseInputs: { paper: 20, grain: 80 },
    constructionCost: { grain: 12000 },
    productionMethods: ['basic_education', 'standardized_education'],
  },
];

export const BUILDING_TYPES_BY_ID = Object.fromEntries(BUILDING_TYPES.map((building) => [building.id, building]));

export const BUILDING_CATEGORIES = [
  { id: 'agriculture', name: '农业' },
  { id: 'industry', name: '工业' },
  { id: 'commerce', name: '商业' },
  { id: 'services', name: '服务' },
  { id: 'infrastructure', name: '基建' },
  { id: 'military', name: '军事' },
];
