const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const hasBuilding = (state, id, min = 1) => Number(state?.buildings?.[id]?.count ?? 0) >= min;
const popTotal = (state) => Number(state?.population?.totalPopulation ?? 0);
const getCommodity = (state, key) => Number(state?.commodities?.[key] ?? 0);

export const EVENT_CATEGORIES = {
  economy: '经济',
  society: '社会',
  diplomacy: '外交',
  environment: '天灾',
  governance: '政务',
};

export const EVENT_DEFINITIONS = [
  { id: 'econ_bumper_harvest', category: 'economy', title: '丰收之年', description: '风调雨顺，粮食增产。', baseWeight: 10, condition: () => true, apply: (state) => { const bonus = Math.round(Math.max(20000, getCommodity(state, 'grain') * 0.05)); state.commodities.grain += bonus; return `粮食库存 +${bonus}`; } },
  { id: 'econ_market_boom', category: 'economy', title: '市集繁荣', description: '商路活跃，商税提升。', baseWeight: 9, condition: (state) => Number(state?.world?.operatingShops ?? 0) > 0, apply: (state) => { const boost = Math.round(Math.max(5000, Number(state?.world?.commerceGDP ?? 0) * 0.05)); state.world.commerceGDP = Math.max(0, Number(state.world.commerceGDP ?? 0) + boost); return `商业GDP +${boost}`; } },
  { id: 'econ_tool_shortage', category: 'economy', title: '铁器短缺', description: '铁器供给不足影响生产。', baseWeight: 7, condition: (state) => getCommodity(state, 'iron_tools') < 10, apply: (state) => { state.world.farmEfficiency = clamp(Number(state.world.farmEfficiency ?? 1) * 0.95, 0.6, 2); return '农业效率 -5%'; } },
  { id: 'econ_craft_innovation', category: 'economy', title: '工坊改良', description: '工匠改良工序，产能提升。', baseWeight: 8, condition: (state) => hasBuilding(state, 'blacksmith', 1) || hasBuilding(state, 'kiln', 1), apply: (state) => { state.world.constructionCostReduction = Math.max(0, Number(state.world.constructionCostReduction ?? 0) + 0.03); return '建设成本再降低 3%'; } },
  { id: 'soc_rural_festival', category: 'society', title: '乡社祭礼', description: '民间庆典，农民士气回升。', baseWeight: 10, condition: () => true, apply: (state) => { state.world.farmerSatisfaction = clamp(Number(state.world.farmerSatisfaction ?? 50) + 4, 0, 100); return '农民满意度 +4'; } },
  { id: 'soc_merchant_dispute', category: 'society', title: '商帮纠纷', description: '商人之间爆发纠纷，市场秩序受扰。', baseWeight: 7, condition: (state) => Number(state?.world?.merchantPopulation ?? 0) > 0, apply: (state) => { state.world.merchantSatisfaction = clamp(Number(state.world.merchantSatisfaction ?? 50) - 6, 0, 100); state.world.commerceGDP = Math.max(0, Number(state.world.commerceGDP ?? 0) * 0.97); return '商人满意度 -6，商业GDP -3%'; } },
  { id: 'soc_public_health_drive', category: 'society', title: '义诊施药', description: '药局开施义诊，公共健康改善。', baseWeight: 8, condition: (state) => hasBuilding(state, 'medicine_hall', 1) || getCommodity(state, 'medicine') > 0, apply: (state) => { state.world.healthIndex = clamp(Number(state.world.healthIndex ?? 60) + 5, 0, 150); return '健康指数 +5'; } },
  { id: 'soc_literacy_wave', category: 'society', title: '启蒙风潮', description: '学堂扩散，识字率提升。', baseWeight: 7, condition: (state) => hasBuilding(state, 'school_primary', 1), apply: (state) => { state.world.farmerLiteracy = clamp(Number(state.world.farmerLiteracy ?? 0.05) + 0.01, 0, 1); state.world.overallLiteracy = clamp(Number(state.world.overallLiteracy ?? 0.05) + 0.008, 0, 1); return '识字率提升'; } },
  { id: 'dip_border_friction', category: 'diplomacy', title: '边市摩擦', description: '边境商旅发生冲突，外交关系受损。', baseWeight: 7, condition: (state) => Number(state?.foreignPolities?.xikou?.diplomacy?.diplomaticContact ?? 0) === 1, apply: (state) => { const xikou = state.foreignPolities?.xikou; if (!xikou) return '无效'; xikou.diplomacy.attitudeToPlayer = clamp(Number(xikou.diplomacy.attitudeToPlayer ?? 0) - 8, -100, 100); return '溪口态度 -8'; } },
  { id: 'dip_envoy_success', category: 'diplomacy', title: '使节凯旋', description: '使节交涉成功，互信上升。', baseWeight: 8, condition: (state) => Number(state?.foreignPolities?.xikou?.diplomacy?.diplomaticContact ?? 0) === 1, apply: (state) => { const xikou = state.foreignPolities?.xikou; if (!xikou) return '无效'; xikou.diplomacy.attitudeToPlayer = clamp(Number(xikou.diplomacy.attitudeToPlayer ?? 0) + 10, -100, 100); xikou.diplomacy.trust = clamp(Number(xikou.diplomacy.trust ?? 40) + 6, 0, 100); return '溪口态度 +10，信任 +6'; } },
  { id: 'dip_trade_route_incident', category: 'diplomacy', title: '商路遇袭', description: '商路遇袭导致运力下降。', baseWeight: 6, condition: (state) => Number(state?.tradeRoutes?.xikou?.annualCapacity ?? 0) > 0, apply: (state) => { const route = state.tradeRoutes?.xikou; if (!route) return '无效'; route.annualCapacity = Math.max(10000, Math.round(Number(route.annualCapacity ?? 0) * 0.85)); route.remainingCapacity = Math.max(0, Math.min(route.remainingCapacity ?? 0, route.annualCapacity)); return '溪口商路年运力 -15%'; } },
  { id: 'dip_new_contact', category: 'diplomacy', title: '北方商情改善', description: '北方商队释放善意信号。', baseWeight: 6, condition: (state) => Boolean(state?.foreignPolities?.northernTraders), apply: (state) => { const traders = state.foreignPolities?.northernTraders; if (!traders) return '无效'; traders.diplomacy.attitudeToPlayer = clamp(Number(traders.diplomacy.attitudeToPlayer ?? 0) + 6, -100, 100); traders.diplomacy.trust = clamp(Number(traders.diplomacy.trust ?? 30) + 5, 0, 100); return '北方商队态度 +6，信任 +5'; } },
  { id: 'env_drought', category: 'environment', title: '春旱', description: '降雨不足导致粮产受损。', baseWeight: 6, condition: () => true, apply: (state) => { state.world.farmEfficiency = clamp(Number(state.world.farmEfficiency ?? 1) * 0.9, 0.5, 2); const loss = Math.round(Math.max(10000, getCommodity(state, 'grain') * 0.03)); state.commodities.grain = Math.max(0, getCommodity(state, 'grain') - loss); return `农业效率 -10%，粮食 -${loss}`; } },
  { id: 'env_flood_relief', category: 'environment', title: '河患赈济', description: '洪涝发生，需赈济灾民。', baseWeight: 5, condition: (state) => popTotal(state) > 10000, apply: (state) => { const cost = 15000; state.world.grainTreasury = Math.max(0, Number(state.world.grainTreasury ?? 0) - cost); state.world.stabilityIndex = clamp(Number(state.world.stabilityIndex ?? 80) + 2, 0, 100); return `赈灾消耗粮食 ${cost}，稳定度 +2`; } },
  { id: 'env_good_weather', category: 'environment', title: '雨水调匀', description: '天气平稳，恢复生产信心。', baseWeight: 8, condition: () => true, apply: (state) => { state.world.farmEfficiency = clamp(Number(state.world.farmEfficiency ?? 1) * 1.05, 0.5, 2); return '农业效率 +5%'; } },
  { id: 'env_forest_bounty', category: 'environment', title: '山林丰材', description: '木材与炭料采集大丰收。', baseWeight: 6, condition: (state) => hasBuilding(state, 'lumber_yard', 1), apply: (state) => { const lumber = 2000; const charcoal = 1500; state.commodities.lumber = getCommodity(state, 'lumber') + lumber; state.commodities.charcoal = getCommodity(state, 'charcoal') + charcoal; return `木材 +${lumber}，木炭 +${charcoal}`; } },
  { id: 'gov_tax_audit', category: 'governance', title: '税务稽核', description: '税吏清查漏税，国库增收。', baseWeight: 8, condition: () => true, apply: (state) => { const gain = 12000; state.world.grainTreasury = Math.max(0, Number(state.world.grainTreasury ?? 0) + gain); return `国库粮食 +${gain}`; } },
  { id: 'gov_bureaucratic_delay', category: 'governance', title: '文牍迟滞', description: '文书积压，行政效率受挫。', baseWeight: 6, condition: () => true, apply: (state) => { state.world.officialEfficiency = clamp(Number(state.world.officialEfficiency ?? 1) * 0.92, 0.4, 2); return '官僚效率 -8%'; } },
  { id: 'gov_reform_push', category: 'governance', title: '政务整饬', description: '行政整顿，制度执行力增强。', baseWeight: 7, condition: () => true, apply: (state) => { state.world.officialEfficiency = clamp(Number(state.world.officialEfficiency ?? 1) * 1.06, 0.4, 2); state.world.stabilityIndex = clamp(Number(state.world.stabilityIndex ?? 80) + 1, 0, 100); return '官僚效率 +6%，稳定度 +1'; } },
  { id: 'gov_corruption_case', category: 'governance', title: '贪腐案发', description: '官吏贪腐曝光，民意受损。', baseWeight: 5, condition: () => true, apply: (state) => { state.world.stabilityIndex = clamp(Number(state.world.stabilityIndex ?? 80) - 4, 0, 100); state.world.fireLeakageRate = clamp(Number(state.world.fireLeakageRate ?? 0.05) + 0.01, 0, 0.5); return '稳定度 -4，火耗率 +1%'; } },
];
